name: Daily Auto Commit

on:
  schedule:
    - cron: "0 5 * * *" # daily 10:30 AM IST approx
  workflow_dispatch: # manual run allowed

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Log File
        run: |
          echo "Updated on $(date)" >> daily-log.txt

      - name: Commit changes
        run: |
          git config --global user.name "Anjali-Bot"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Automated update: $(date)" || echo "No changes to commit"
          git push
